name: Build Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install required tools, Vulkan, and shaderc
      - name: Install required tools and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            build-essential \
            libepoxy-dev \
            vulkan-tools \
            libvulkan-dev \
            mesa-vulkan-drivers \
            libshaderc-dev \
            shaderc

      # Step 3: Verify Vulkan and Shaderc (Optional)
      - name: Verify Vulkan and Shaderc installation
        run: |
          vulkaninfo || echo "vulkaninfo not available"
          shaderc -h || echo "shaderc not available"

      # Step 4: Configure and Build the project
      - name: Configure and Build
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      # Step 5: Debugging (Optional) - Show CMakeCache.txt if errors persist
      - name: Debug CMake Cache (Optional)
        if: failure()
        run: cat build/CMakeCache.txt
