name: Install and Compile on Arch Linux

on:
  workflow_dispatch:

jobs:
  build-arch:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Install Build Tools
        run: |
          pacman -Sy --noconfirm base-devel git

      - name: Clone and Compile Project
        run: |
          git clone https://github.com/archlinux/svntogit-packages.git /build/project
          cd /build/project
          makepkg -si --noconfirm

      # Uncomment and edit the following to upload a build artifact if needed
      # - name: Upload build artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: build-output
      #     path: /build/project/output/
