name: Build Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install necessary build tools
      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      # Build the project
      - name: Configure and Build
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
