name: Build Blender on Ubuntu with Docker

on:
  workflow_dispatch:

jobs:
  build-blender:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Blender inside Ubuntu Docker container
        run: |
          docker pull ubuntu:22.04
          docker run --rm -v $PWD:/workspace -w /workspace ubuntu:22.04 bash -c "
            apt-get update &&
            DEBIAN_FRONTEND=noninteractive apt-get install -y \
              git build-essential cmake ninja-build gcc g++ \
              python3 python3-numpy python3-requests python3-setuptools \
              libboost-all-dev libeigen3-dev libopenimageio-dev \
              libopenvdb-dev libopenexr-dev libopenal-dev ffmpeg \
              libopencolorio-dev libglfw3-dev libglew-dev libfreetype6-dev \
              libtbb-dev libsdl2-dev libalembic-dev libopenxr-dev \
              libvulkan-dev libwayland-dev libxi-dev libx11-dev \
              libxcursor-dev libxrandr-dev libxinerama-dev libepoxy-dev \
              libpng-dev libjpeg-dev zlib1g-dev libtiff-dev libjemalloc-dev \
              libomp-dev libspnav-dev libfftw3-dev libembree-dev \
              libusd-dev fontconfig libharfbuzz-dev xz-utils liblzma-dev \
              libxml2-dev libhdf5-dev libjson-c-dev wget &&
            git clone --depth 1 https://github.com/blender/blender.git /blender &&
            cd /blender &&
            git submodule update --init --recursive &&
            mkdir build &&
            cd build &&
            cmake .. -G Ninja &&
            ninja
          "

      # Uncomment below to upload Blender binary as artifact
      # - name: Upload Blender Binary
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: blender-binary
      #     path: blender/build/bin/blender
